### ISSUE TITLE
Training settings

### ISSUE THREAD

**Issue by ymxlzgy** [StanfordVL/JRMOT_ROS#1]
Hi Abhijeet!
Congratulations to your work and thank you for sharing your code to the whole community. But I want to ask how I can train your model as I didn't see the related instruction in README you released.

Best regards!

**Comment by liuqi8827** [comment]
Hi,

Thanks for your great work!
Can this this project run successfully?

**Comment by mvpatel2000** [comment]
Closing as this seems outdated. Apologies for not responding earlier. I am not sure what model or component (ie object detector, appearance features) you are specifically referencing, but feel free to open a new issue which is more detailed.

**Comment by Ademord** [comment]
How do we use JRMOT? do you have a tutorial on custom objects?
