### ISSUE TITLE
About JPDA

### ISSUE THREAD

**Issue by wangx1996** [StanfordVL/JRMOT_ROS#13]
Hello， I read your code， but I cannot find where is the JPDAF moduel, would you please tell me which file is the implementation of the JPDAF?

**Comment by mvpatel2000** [comment]
Please refer to:
https://github.com/StanfordVL/JRMOT_ROS/blob/master/src/JPDA_matching.py (the wrapper class) 
and
https://github.com/StanfordVL/JRMOT_ROS/blob/9cbb1e2acf4dff8152f65dd32a1b6f5961fc5125/src/linear_assignment.py
