### ISSUE TITLE
Run on KITTI dataset

### ISSUE THREAD

**Issue by zhanghming** [StanfordVL/JRMOT_ROS#4]
Hi, thanks for your great work. I wonder how did you run your code on KITTI tracking dataset?

Is there any pretrained model on KITTI tracking dataset?

**Comment by mvpatel2000** [comment]
Hi @zhanghming, can you please provide your email and/or reach out to mihirp@stanford.edu? I can share the code we used for KITTI along with weights.

**Comment by zhanghming** [comment]
@mvpatel2000 , OK, it's so kind of you, thanks you very much. And I have already sent you an email.
