### ISSUE TITLE
Gurobi installation for ARM

### ISSUE THREAD

**Issue by Eashwar93** [StanfordVL/JRMOT_ROS#5]
Hello,
Thanks a lot for the great work.

I'm trying to implement JRMOT in a robot that we are building. We make extensive use of Nvidia Xavier computers which are based on ARM architectures. 

Unfortunately one of the dependencies of this package being Gurobi solver is not available for ARM based architecture. Is there a round about this solver? 

Also I'm unable to find in which of the source code file Gurobi is being used. If I could have a look at it, I might try to replace it available solvers for ARM architecture.

Thanks a lot!

**Comment by mvpatel2000** [comment]
We use Gurobi in the following file: https://github.com/StanfordVL/JRMOT_ROS/blob/master/src/mbest_ilp.py.

I do not have experience using other solvers or much with the ARM architecture, but I believe there should be other solvers that can do the same constraint satisfaction problem. Closing this issue now, feel free to reopen if you have follow-up questions.
