### ISSUE TITLE
System setup

### ISSUE THREAD

**Issue by Eashwar93** [StanfordVL/JRMOT_ROS#6]
Hello again,

I'm trying to setup the computer(NVIDIA Xavier) to use your package with ROS

From the code I guess package depends on the following ML frameworks:
1. Pytorch - for Re-ID of Image Features
2. Tensorflow - for 3D detection

I'm a bit confused as to how to setup the computer as ROS depends on Python-2 and the current git code-base for Pytorch is supported only for python3 onwards and only a few older versions of TF can be setup with python2. It would be nice if you could shed some light on system setup so that I can test the package on my computer as well.

Also, if you could tell which version of Tensorflow and Pytorch does this package depend on in your readme, that would be great.

Cheers to the great work !!

**Comment by abhijeetshenoi** [comment]
Hello!
These are great questions you've brought up. The decision to write the code in Python 2, was that for most of last year, we worked with ROS and our entire ROS stack is in Python2.
There is python3 compatible code under the paper_experiments folder - [here](https://github.com/StanfordVL/JRMOT_ROS/tree/master/paper_experiments) which you can use as reference, but the ROS implementation is currently only available in Python2
